### ISSUE TITLE
Any issues moving pangeo.esipfed.org to this framework?

### ISSUE THREAD

**Issue by rsignell-usgs** [pangeo-data/pangeo-cloud-federation#188]
I'm currently running pangeo.esipfed.org on the pangeo-access AWS kops cluster the old way:  manually executing the `docker build`, pushing to dockerhub, and re-upping the helm chart.   

I would like to move to the new approach.   Anything I should be aware of?

**Comment by scottyhq** [comment]
@rsignell-usgs we're actively working on the AWS EKS 'icesat2' deployment. So that is where you'll want to look for the most recent configuration. As far as setting up the kubernetes cluster, we plan to post our notes here in the near future https://github.com/jhamman/ACCESS_K8S, but we're using a combination of [eksctl](https://github.com/weaveworks/eksctl), [cluster autoscaler](https://eksworkshop.com/scaling/deploy_ca), and an EFS drive created in the console

**Comment by rsignell-usgs** [comment]
Do you have autoscaling and spot market working with EKS now?  That was the reason I was sticking with kops.

**Comment by scottyhq** [comment]
autoscaling is working currently, but we haven't tackled spot instances yet (hopefully soon!). In any case, this repository takes care of deploying the jupyterhub pieces after kubernetes setup, so you could create a new 'esip' deployment and point to your existing kops cluster (or create a duplicate for testing).

**Comment by rsignell-usgs** [comment]
Cool, that's what I was hoping.  I'll try that.

**Comment by rabernat** [comment]
Is this resolved?

**Comment by scottyhq** [comment]
closing since esip.pangeo.io now lives here.
