### ISSUE TITLE
dev.pangeo.io - Only 51% of worker nodes utilized

### ISSUE THREAD

**Issue by consideRatio** [pangeo-data/pangeo-cloud-federation#276]
I found in the cloud console that we have a lot of nodes that are underutilized, because they have pods scheduled on them that request 50% of the nodes memory. I bet the person scheduling these pods aim to get two pods per node but is actually ending up with only one pod per node by mistake.

![image](https://user-images.githubusercontent.com/3837114/57578693-80b5f880-7491-11e9-9272-e32e60854f6e.png)

Inspecting the node further, one can see that there are some system pods scheduled on each node related to logging and such, these will always eat up some resources.

![image](https://user-images.githubusercontent.com/3837114/57578716-edc98e00-7491-11e9-9c76-c7b1fdf43f0b.png)

Reducing the request to 11.5 would solve this. I'm currently too fresh on this code base to figure out what to do with this insight so I figured I'd write it here.

**Comment by jhamman** [comment]
Thanks for bringing this up @consideRatio. I think we have a few things we can do here. 

1. Finish up the dask-kubernetes taints/affinity PRs (https://github.com/dask/dask-kubernetes/pull/147)
2. Come up with a way to document/publish k8s cluster configurations to help users better determine appropriate pod specs. 
3. Work on getting grafana dashboards setup for these clusters so people can see the cluster usage without being an admin on the GCP account (see https://github.com/pangeo-data/helm-chart/pull/88)
4. Experiment with GKE's [node auto-provisioning](https://cloud.google.com/kubernetes-engine/docs/how-to/node-auto-provisioning) for dask-workers.

I think, by chance, I've ordered these appropriately, in terms of both ease and relevance. What do you think?

**Comment by consideRatio** [comment]
@jhamman that sounds very practical and suitable!

**Comment by jhamman** [comment]
@rabernat - can we get you (or @raphaeldussin) to reduce the memory requirement in the dask-worker config for ocean.pangeo.io: https://github.com/pangeo-data/pangeo-cloud-federation/blob/8f7f4bf9963ef1ed180dd20c952ff1aa8df54ca2/deployments/ocean/image/binder/dask_config.yaml#L32

11.5G would be fine. You might as well also ask for more cpu (1.75?) since there is more to be had on these nodes.

**Comment by consideRatio** [comment]
@jhamman I think it is often best to let the request be quite low and the limit quite high for CPU, while you request/limit similarly for memory.

It makes it easier to accomplish max CPU utilization.

**Comment by rabernat** [comment]
I am absolutely fine with tweaking these settings. They were somewhat arbitrary. We increased up from the standard settings because we had nodes running out of memory and crashing.

@consideRatio - one unique aspect of our usage here is that we are very rarely CPU bound. A primary application of dask in Pangeo is to improve throughput of I/O bound tasks by leveraging the parallelism of cloud storage. So max CPU utilization may be the wrong target.

**Comment by rabernat** [comment]
A related issue is how best to configure our profile lists to match the available node resources:

This is what we currently have for notebooks:
https://github.com/pangeo-data/pangeo-cloud-federation/blob/8f7f4bf9963ef1ed180dd20c952ff1aa8df54ca2/deployments/ocean/config/common.yaml#L36-L75

The x-large option never launches because no node from our nodepools can meet its requirements. I would love to have some suggestions on how to refine this profile_list.
