### ISSUE TITLE
csiro.pangeo.io ?

### ISSUE THREAD

**Issue by jmunroe** [pangeo-data/pangeo-cloud-federation#285]
I've been working on deploying an AWS-based (using EKS and eksctl, on ap-southeast-2) Pangeo JupyterHub for CSIRO.  Rather than duplicating efforts in a separate repo, perhaps a better way forward is to integrate my efforts within this repository?  Would it be appropriate to hang a csiro subdomain off of pangeo.io ?

**Comment by scottyhq** [comment]
Hi @jmunroe! While this is certainly possible, and there are some benefits to having things consolidated, there are some downsides as well:

- anyone utilizing this repo has access to the Cloud account credentials of other projects in the repo (b/c git-crypt unlocks the keys for all deployments).

- this hasn't been so much of a concern b/c their are few repo admins, and all hubs are either supported by a grant including google cloud credits or a related grant w/ aws credits

- all hubs here have whitelist access for github pangeo-data members (this isn't really required, but makes sense because of the funding). 

So, it might make more sense to create a fork and deploy separately? In theory, the only manual step is creating a circleci project with your own GIT_CRYPT_KEY (https://github.com/pangeo-data/pangeo-cloud-federation/blob/staging/.circleci/config.yml#L145). Other groups are going this route. here are some related issues: #32, #39, #181, #263

**Comment by rabernat** [comment]
> * all hubs here have whitelist access for github pangeo-data members (this isn't really required, but makes sense because of the funding).

Actually this can be configured separately for each hub.

**Comment by jmunroe** [comment]
I am going down the route of forking and deploying separately. I've been able to copy and modify a previous deployment, got git_crypt working, set things up with CircleCI, built the image.  Currently trying to get helm (hubploy deploy) to successfully complete.  I'll post here if I hit a blocking issue. Thanks.

**Comment by jmunroe** [comment]
Both the staging and prod deployments for pangeo-csiro are are now working. I think the NFS storage is working and I still need to test out the dask worker scaling.

Thanks so much @scottyhq ! I've been mostly successfully by trying to replicate a good chunk of what you have recently been doing.
