### ISSUE TITLE
Really long wait time to compute 

### ISSUE THREAD

**Issue by shanicetbailey** [pangeo-data/pangeo-cloud-federation#322]
Hi,

I'm a new user to pangeo and I have a couple potential issues when I try computing a heat budget using SOSE model.
1) I've tried to run a simple SST calculation using Kubernetes clusters, and the wait time is 10 minutes or more. 
2) I've only been seeing 1 worker available on my widget - even when I try to do a more expensive computation like advective fluxes.
3) When I click the link to look at the dask dashboard to see the progress, I don't see anything happening when I click on 'Task' bar. But when I click on 'Workers' bar, I do see "CPU Use" activity for the one worker in my notebook.

I've attached an example code for computing SST. I'd appreciate anyone who can explain to me what exactly is going on, and if there is even an issue present... I think there may be just because I've done the same exact calculation on Gyre with local clusters and wait time was not nearly as long (and I expected pangeo to outperform that server)
[example_code.pdf](https://github.com/pangeo-data/pangeo-cloud-federation/files/3370375/example_code.pdf)
. Thank you!

**Comment by rabernat** [comment]
Thanks @stb2145 for reporting this important issue.

The first problem is that you are not connecting to the cluster. You need to run:
```python
client = Client(cluster)
```
otherwise your notebook will not send any computations through the cluster.

The next problem is that you are using the cluster in adaptive mode, i.e.
```python
cluster.adapt(minimum=1, maximum=10) 
```

What this does is to create adaptively scaling cluster, which adjusted the number of nodes between 1 and 10 based on the perceived load. Ideally this allows us to optimize resource usage among many users. But the problem is that the worker nodes are very, very slow to boot up (like 5 minutes). In this case, adaptive scaling becomes useless, because the cluster can't scale up fast enough. If you want to be sure to have a fixed number of workers, you can do
```python
cluster.scale(10)
```

With these two changes, things should improve greatly.

**Comment by shanicetbailey** [comment]
Indeed, improvement achieved! Thank you @rabernat!
