### ISSUE TITLE
Staging deployments broken following helm chart version bump

### ISSUE THREAD

**Issue by jhamman** [pangeo-data/pangeo-cloud-federation#560]
I merged a minor version bump from our helm chart into staging a few hours ago. All deployments failed to deploy with the following error message:

```
...
Saving 1 charts
Downloading pangeo from repo https://pangeo-data.github.io/helm-chart/
Deleting outdated charts
Error: UPGRADE FAILED: cannot patch "autohttps" with kind Deployment: Deployment.apps "autohttps" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app":"jupyterhub", "component":"autohttps", "release":"dev-staging"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
Traceback (most recent call last):
  File "/home/circleci/repo/venv/bin/hubploy", line 11, in <module>
    load_entry_point('hubploy==0.1.0', 'console_scripts', 'hubploy')()
  File "/home/circleci/repo/venv/lib/python3.7/site-packages/hubploy/__main__.py", line 89, in main
    helm.deploy(args.deployment, args.chart, args.environment, args.namespace, args.set, args.version, args.timeout, args.force)
  File "/home/circleci/repo/venv/lib/python3.7/site-packages/hubploy/helm.py", line 129, in deploy
    force
  File "/home/circleci/repo/venv/lib/python3.7/site-packages/hubploy/helm.py", line 65, in helm_upgrade
    subprocess.check_call(cmd)
  File "/usr/local/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['helm', 'upgrade', '--wait', '--install', '--namespace', 'dev-staging', 'dev-staging', 'pangeo-deploy', '-f', 'deployments/dev/config/common.yaml', '-f', 'deployments/dev/config/staging.yaml', '-f', 'deployments/dev/secrets/staging.yaml', '--set', 'pangeo.jupyterhub.singleuser.image.tag=de4c2da', '--set', 'pangeo.jupyterhub.singleuser.image.name=gcr.io/*************/dev-pangeo-io-notebook']' returned non-zero exit status 1.

Exited with code exit status 1
```

Tests on my PR and upstream in our helm chart repo passed prior to merging.

- helm chart PR: https://github.com/pangeo-data/helm-chart/pull/120
- helm chart tests: https://circleci.com/gh/pangeo-data/helm-chart/82
- version bump PR: https://github.com/pangeo-data/pangeo-cloud-federation/pull/559
- version bump tests: https://circleci.com/gh/pangeo-data/pangeo-cloud-federation/1149

pinging @yuvipanda and @consideRatio to ask if they have seen this recently? And @scottyhq, @tjcrone, and @TomAugspurger as a heads up that some manual correction is likely necessitated.

**Comment by consideRatio** [comment]
Thanks for pining me! The complaint helm makes relates to some fields of a k8s resource require the entire resource to be replaced rather than upgraded, and this is one such change. For those, the `--force` flag is required.

```
      --force                    force resource updates through a replacement strategy
```

This means that a `kubectl replace` operation is used in the latest version of `helm` as seen in their [source code](https://github.com/bacongobbler/helm/blob/4d5a62303ef45ea56d479f5b7086742e532772d7/pkg/kube/client.go#L393-L399). But, it seems from reading `kubectl replace --help` that we can also pass `--force` there, and only that will cause a delete / create cycle, while not using `--force` on the `kubectl replace` command will do something else somehow? Hmm... I'm confused in general about what `--force` does, and what it does in various versions of helm / kubernetes.

I think in general it can make sense to use `--force` all the time, because I've never been in a situation where I would not recommend using `--force` when this situation arise.

**Comment by consideRatio** [comment]
You caught this because you are testing the acquisition of https certificates and the upgrade process between version, while the main z2jh helm chart test the upgrade process from 0.8.2 with some kind of configuration, this configuration does not include an automatic certificate acquisition because it is hard to test.

Related: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1565

**Comment by jhamman** [comment]
Thanks @consideRatio - I tried adding `--force`. Deploying to staging.hub.pangeo.io works locally but is failing on our CICD system. All hubs fail with this error:

```
Error: UPGRADE FAILED: rendered manifests contain a new resource that already exists. Unable to continue with update: existing resource conflict: kind: ConfigMap, namespace: icesat2-staging, name: traefik-proxy-config
Traceback (most recent call last):
  File "/home/circleci/repo/venv/bin/hubploy", line 11, in <module>
    sys.exit(main())
  File "/home/circleci/repo/venv/lib/python3.7/site-packages/hubploy/__main__.py", line 89, in main
    helm.deploy(args.deployment, args.chart, args.environment, args.namespace, args.set, args.version, args.timeout, args.force)
  File "/home/circleci/repo/venv/lib/python3.7/site-packages/hubploy/helm.py", line 129, in deploy
    force
  File "/home/circleci/repo/venv/lib/python3.7/site-packages/hubploy/helm.py", line 65, in helm_upgrade
    subprocess.check_call(cmd)
  File "/usr/local/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['helm', 'upgrade', '--wait', '--install', '--namespace', 'icesat2-staging', 'icesat2-staging', 'pangeo-deploy', '--force', '-f', 'deployments/icesat2/config/common.yaml', '-f', 'deployments/icesat2/config/staging.yaml', '-f', 'deployments/icesat2/secrets/staging.yaml', '--set', 'pangeo.jupyterhub.singleuser.image.tag=8cd0208', '--set', 'pangeo.jupyterhub.singleuser.image.name=783380859522.dkr.ecr.us-west-2.amazonaws.com/pangeo']' returned non-zero exit status 1.
```

**Comment by consideRatio** [comment]
@jhamman I think this is now a consequence of a failed initial attempt =/

I would try to delete that configmap, and then run again. I think the logic of helm is like this:
1. Helm: Oh lets create some resources (traefik-proxy-config).
2. Helm: Oh no, i cannot finish this installation, I would be require --force for this! ABORT!
3. You: Use --force Helm!
4. Helm: Oh but hey there is a new resource there, that I would replace, but I know nothing about this resource (traefik-proxy-config).

So, I think what needs to be done, is to clean up the partial installation that failed. I consider it a helm bug to need to manually cleanup.

**Comment by jhamman** [comment]
I've been working on cleaning up the partial/failed deployment:

```bash
$ kubectl delete role autohttps --namespace hydro-staging
role.rbac.authorization.k8s.io "autohttps" deleted
$ kubectl delete configmap traefik-proxy-config --namespace hydro-staging
Error from server (NotFound): configmaps "traefik-proxy-config" not found
$ kubectl delete configmap nginx-proxy-config --namespace hydro-staging
Error from server (NotFound): configmaps "nginx-proxy-config" not found
$ helm upgrade --wait --install --namespace hydro-staging hydro-staging pangeo-deploy -f deployments/hydro/config/common.yaml -f deployments/hydro/config/staging.yaml -f deployments/hydro/secrets/staging.yaml --force
Error: UPGRADE FAILED: rendered manifests contain a new resource that already exists. Unable to continue with update: existing resource conflict: namespace: hydro-staging, name: autohttps, existing_kind: rbac.authorization.k8s.io/v1, Kind=RoleBinding, new_kind: rbac.authorization.k8s.io/v1, Kind=RoleBinding
```

This is odd though. In line 1, I remove `autohttps`, then the last line errors because it has found `autohttps` again. Suggestions?

**Comment by salvis2** [comment]
@jhamman The first line is deleting the `role`, while the last line is the `RoleBinding`. I think you need a `kubectl delete rolebinding` command.

**Comment by jhamman** [comment]
Thanks @salvis2! That gets us closer. Maybe the next question is for @TomAugspurger:

```bash
helm upgrade --wait --install --namespace hydro-staging hydro-staging pangeo-deploy -f deployments/hydro/config/common.yaml -f deployments/hydro/config/staging.yaml -f deployments/hydro/secrets/staging.yaml --force
Error: UPGRADE FAILED: failed to replace object: Service "gateway-api-hydro-staging-dask-gateway" is invalid: spec.clusterIP: Invalid value: "": field is immutable && failed to replace object: Service "scheduler-api-hydro-staging-dask-gateway" is invalid: spec.clusterIP: Invalid value: "": field is immutable && failed to replace object: Service "scheduler-public-hydro-staging-dask-gateway" is invalid: spec.clusterIP: Invalid value: "": field is immutable && failed to replace object: Service "web-api-hydro-staging-dask-gateway" is invalid: spec.clusterIP: Invalid value: "": field is immutable && failed to replace object: Service "web-public-hydro-staging-dask-gateway" is invalid: spec.clusterIP: Invalid value: "": field is immutable && failed to replace object: Service "hub" is invalid: spec.clusterIP: Invalid value: "": field is immutable && failed to replace object: Service "proxy-http" is invalid: spec.clusterIP: Invalid value: "": field is immutable && failed to replace object: Service "proxy-api" is invalid: spec.clusterIP: Invalid value: "": field is immutable && failed to replace object: Service "proxy-public" is invalid: spec.clusterIP: Invalid value: "": field is immutable && failed to replace object: Deployment.apps "gateway-hydro-staging-dask-gateway" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/component":"gateway", "app.kubernetes.io/instance":"hydro-staging", "app.kubernetes.io/managed-by":"Helm", "app.kubernetes.io/name":"dask-gateway"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable && failed to replace object: Deployment.apps "scheduler-proxy-hydro-staging-dask-gateway" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/component":"scheduler-proxy", "app.kubernetes.io/instance":"hydro-staging", "app.kubernetes.io/managed-by":"Helm", "app.kubernetes.io/name":"dask-gateway"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable && failed to replace object: Deployment.apps "web-proxy-hydro-staging-dask-gateway" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/component":"web-proxy", "app.kubernetes.io/instance":"hydro-staging", "app.kubernetes.io/managed-by":"Helm", "app.kubernetes.io/name":"dask-gateway"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable && failed to replace object: Deployment.apps "autohttps" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app":"jupyterhub", "component":"autohttps", "release":"hydro-staging"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
```

**Comment by TomAugspurger** [comment]
Possibly https://github.com/dask/dask-gateway/issues/201?

```
$ kubectl get deployment/gateway-hydro-staging-dask-gateway -n hydro-staging -o yaml | sed "s/Tiller/Helm/g" | kubectl replace --force=true -f -
$ kubectl get deployment/scheduler-proxy-hydro-staging-dask-gateway -n hydro-staging -o yaml | sed "s/Tiller/Helm/g" | kubectl replace --force=true -f -
$ kubectl get deployment/web-proxy-hydro-staging-dask-gateway -n hydro-staging -o yaml | sed "s/Tiller/Helm/g" | kubectl replace --force=true -f -
```

I though that would be a one-time thing though.

**Comment by TomAugspurger** [comment]
Mmm I guess the error message is a bit different. "Failed to replace object" vs. "cannot patch". So perhaps not the same issue.

**Comment by salvis2** [comment]
@jhamman , it looks like (roughly) the first half of the objects helm can't replace are `spec.clusterIP`s, which is probably something that Helm isn't assigning, right? Those would be assigned by kubernetes after the resources are created. 

I'm looking at [this comment](https://github.com/helm/helm/issues/6378#issuecomment-557746499) which details why this happens in another case (maybe the same here): a three way patch gone wrong. This only applies if the charts involved are actually setting `spec.clusterIP` to "" by default.

The fix on specifying `spec.clusterIP` didn't work for a lot of people because they were never specifying it manually in the first place, see this [issue](https://github.com/helm/helm/issues/7350). Basically the `--force` flag brings in immutable fields (which it shouldn't do) and then errors out.  The result for this issue was to not use `--force` I think.

@consideRatio I agree that the `--force` flag is confusing. This [comment](https://github.com/helm/helm/issues/7082#issuecomment-559558318) seems helpful:

> Helm 2 used to delete and re-install the resource on a PATCH failure, which led to a lot of cases where things like spurious client timeouts causing the patch to fail would delete the resource... Not exactly what you'd call a great experience.
In Helm 3, the behaviour of --force was refactored to better align with its intent: to force a PUT operation (an overwrite) when the user requests. This allows the user to bypass the three-way merge patch strategy, forcing idempotency and overwriting the object currently maintained by Helm in the cluster.

I don't know what a kubernetes PUT operation is really, but maybe that's helpful for others.

**Comment by scottyhq** [comment]
might be too late for this to be useful but per https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1539#issuecomment-575758090 
seems important to run `kubectl delete deployment autohttps -n NAMESPACE` **before running helm-upgrade**

this would apply to any chart versions that including the https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1539# change from (kube-lego + nginx ingress replaced by traefik)

**Comment by consideRatio** [comment]
Regarding clusterIP being immutable issues, that is a known issue that transitioning from using a clusterIP for a service to acting as a loadBalancer can go wrong. If i recall correctly, the resolution is to manually delete the service first, or make an intermediary patch where the clusterIp is null or similar... :'(

---

> @jhamman The first line is deleting the role, while the last line is the RoleBinding. I think you need a kubectl delete rolebinding command.

@jhamman / @salvis2 yes, this is very troublesome. Because helm will fail on the first issue, it will provide you with information about that, so you delete that resource and repeat and then you get a new issue - but you also created another failed attempt to install the resource, which caused the previous resource to popup again. To properly get all the way, one may need to figure out exactly everything to delete, and then do it. :'( The fact that this can arise from not using --force systematically, at least in helm 2, have made me suggest using --force by default.

---

@scottyhq EXCELLENT catch referencing https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1539#issuecomment-575758090, that is very relevant - to delete the autohttps deployment before upgrading.

Okay! So I guess we have a very clear "breaking change" that needs documentation. Assuming `--force` don't work. I have not tested this from a clean slate and it may work from a clean slate while it may fail when we have already attempted once without and had an upgrade fail.

**Comment by scottyhq** [comment]
> @consideRatio I agree that the --force flag is confusing.

@salvis2 thanks for looking into this a bit more. Take a look at https://github.com/helm/helm/pull/7431 which has a nice table comparing helm options to kubectl options. I suspect this will prove useful going forward, but seems like a feature slated for helm>3.2

@jhamman, @consideRatio and @yuvipanda I'm thinking we want the --force flag off by default for cluster upgrades? If --atomic works as expected we will see the upgrade initial fails and use some combination of --recreate and --force if necessary...

**Comment by consideRatio** [comment]
It seems like the helm chart publishing process to https://pangeo-data.github.io/helm-chart/ has gone wrong, because the latest version, n042, doesn't contain the dependency charts, so that is why we have broken the staging deployments - they successfully upgraded to a helm chart that didn't contain any of the resources from jupyterhub etc.
