### ISSUE TITLE
AWS staging is down

### ISSUE THREAD

**Issue by cspencerjones** [pangeo-data/pangeo-cloud-federation#961]
When I visit https://staging.aws-uswest2.pangeo.io/ I get "Bad Gateway". I am running a [coiled](https://cloud.coiled.io/) cluster, which won't run from the production environment because the dask version is too old. Please can someone look at what might be wrong on staging?

**Comment by rabernat** [comment]
Could this be related to https://github.com/pangeo-data/pangeo-cloud-federation/pull/959 and the failed deployment that followed: https://github.com/pangeo-data/pangeo-cloud-federation/runs/2607424477?check_suite_focus=true

**Comment by scottyhq** [comment]
> I am running a coiled cluster, which won't run from the production environment because the dask version is too old. 

This points to a larger problem of keeping deployments up-to-date (https://github.com/pangeo-data/pangeo-cloud-federation/pull/957). We shouldn't be relying on the 'staging' deployment. It is intended to fail. That said, I might be the only one currently with access to the cluster to look at logs. Would love for someone else to troubleshoot things like this, otherwise I think that we should put up a banner saying the AWS deployment will be taken down in September 2021. cc @jhamman.

**Comment by scottyhq** [comment]
The problem is that the core node (where the hub runs) has the following taint:
```
CreationTimestamp:  Fri, 16 Apr 2021 10:17:59 +1000
Taints:             NodeWithImpairedVolumes=true:NoSchedule
```

I've not seen that before. Hopefully simply deleting the node to get a new one would remedy things.

**Comment by rabernat** [comment]
> Hopefully simply deleting the node to get a new one would remedy things.

Who has permissions to do this? Neither I nor anyone at Columbia has any admin privileges on the AWS account.

**Comment by scottyhq** [comment]
shared the credentials on the pangeo keybase group. With those you can run kubectl commands against the cluster

**Comment by rabernat** [comment]
Thanks for sharing the credentials Scott! Still, we're in a bit of a jam here. I am not able to take on sysadmin duties for the AWS cluster. We have no one at Columbia in a DevOps role.

On the other hand, we have money parked at 2i2c for this sort of work, but the person hired to work on this has not started yet.

Our options are to:
- Let the cluster stay broken for another month or two.
- Beg someone in our network with DevOps knowledge to help fix our cluster pro bono.

Neither option is very appealing. The situation exposes the truly unsustainable state of our current cluster infrastructure.

**Comment by scottyhq** [comment]
i went ahead and took a gamble with `kubectl drain node` and `eksctl scale nodegroup 0` then `eksctl scale nodegroup 1` and it seems like things are back up. Would love for someone else to monitor and maintain this deployment going forward.

**Comment by damianavila** [comment]
I have seen this before (in other JupyterHub spaces, not Pangeo ones) when some pods failed to attach a volume.
That triggered some tainting into the node that prevented further scheduling.
Removing the taint was enough for getting the node responsive again in that case because it was a transient failure...

`kubectl taint nodes fooNode NodeWithImpairedVolumes:NoSchedule-`

Just in case you want to try something else :wink:.

**Comment by rabernat** [comment]
Thanks so much Scott! You're a 🦸!! Yes, I know you are not able to monitor and maintain this deployment. We do have a long-term sustainability plan: 2i2c. We just have to keep the lights on for another month or so before 2i2c can take over.

**Comment by cspencerjones** [comment]
Thanks for taking the time to help us Scott. Everything is working for me.
